### ISSUE TITLE
Validate metadata reference

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#103]
Validate attributes annotated with `[metadata reference]` that the attribute Type has `[metadata key]` annotation

**Comment by TomCLForwood** [comment]
The ultimate requirement is that for any reference in an _instance_ document there has to be an object of the correct type that has the key metafield set with that value.

There are two ways that an object with a key metafield can be declared in rosetta. The first and most common is by adding the key meta tag to a class
The second is by declaring an attribute with the id keyword
e.g.
`class FxFeature <"A type for defining FX Features.">
	[synonym FpML_5_10 value FxFeature]
{
	referenceCurrency string (1..1) id, scheme <"Specifies the reference currency of the trade.">;
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value referenceCurrency meta id, currencyScheme]
	composite Composite (0..1) <"If 'Composite' is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.">;
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value composite]
	/*
	 * The below quanto associated definition makes reference to the Equity definitions.  Is that right, considering the cross-assets use of this construct?
	 */
	quanto Quanto (0..1) <"If 'Quanto' is specified as the Settlement Type in the relevant Transaction Supplement, an amount, as determined by the Calculation Agent in accordance with the Section 8.2 of the Equity Definitions.">;
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value quanto]
	crossCurrency Composite (0..1) <"If 'Cross-Currency' is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier x one unit of the Reference Currency converted into an amount in the Settlement Currency using the rate of exchange of the Settlement Currency as quoted on the Reference Price Source on the Valuation Date, provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.">;
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value crossCurrency]
}`
the referenceCurreny field is created as a FieldWithMetaString object in java and creates a string with a key metafield providing the ability  to reference the string value from elsewhere in the document.

A better statement of the requirement might be
Validate attributes annotated with [metadata reference] that the attribute Type has [metadata key] annotation OR there exists somewhere an attribute of that type annotated with the id keyword

**Comment by dhuebner** [comment]
We will only validate the complex typed attributes

**Comment by dhuebner** [comment]
fixed
