### ISSUE TITLE
condition names: remove type name from condition name

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#107]
In the below example, the name of the first condition should be removed entirely and the name of the second condition should be 'quantityMultiplier' only. The generated java code should compute the name based on the same convention i.e. `<type name>(<condition name>|<condition type><#>)` where condition type should be 'choice' or 'oneof'.

```haskell
type ResolvablePayoutQuantity: 

...

condition ResolvablePayoutQuantity_choice1: <"A payout quantity can be resolved either (i) by fetching its actual quantity from a higher-level quantity notation specification referenced via a tag, or (ii) by reference to another (resolvable) quantity.">
	optional choice  quantityNotationTag, quantityReference

condition ResolvablePayoutQuantity_quantityMultiplier: <"A quantity reference must exist when there is a quantity multiplier on a resolvable quantity">
	if ResolvablePayoutQuantity -> quantityMultiplier exists
	then ResolvablePayoutQuantity -> quantityReference exists
```

**Comment by dhuebner** [comment]
>  i.e. (|<#>)

@jim-h-wang Could you explain what does it mean?

**Comment by jim-h-wang** [comment]
> > i.e. (|<#>)
> 
> @jim-h-wang Could you explain what does it mean?

Oops - lost text due to formatting. Amended original description.

**Comment by SimonCockx** [comment]
It is unclear for me to what this issue refers. Is this...

1. a feature request? I.e., conditions should not have an explicit name, but the name should be auto-generated instead.
2. a documentation issue? I.e., the documentation should mention the naming conventions for conditions.
3. an issue of the CDM? I.e., the CDM currently does not uphold the right naming convention for conditions throughout its code base.

I know this is an old issue, so if this is not relevant anymore, please explain why so this can be closed. :)

**Comment by dhuebner** [comment]
@SimonCockx 
It is merged already, so I think you can just close it

**Comment by SimonCockx** [comment]
@dhuebner Alright, thanks!
