### ISSUE TITLE
Link to CDM repo not working

### ISSUE THREAD

**Issue by naddison36** [REGnosys/rosetta-dsl#11]
The README states "The CDM is hosted separately from the Rosetta DSL in its own [repository](https://github.com/REGnosys/rosetta-cdm)." but the link to https://github.com/REGnosys/rosetta-cdm does not work.

Is the link incorrect? Or is the CDM only privately available?

Nick

**Comment by dhuebner** [comment]
@naddison36 It's private

**Comment by naddison36** [comment]
The Rosetta Language Code Generation diagram on the Rosetta documentation states that the rosetta-cdm repo is Open on GitHub. https://docs.rosetta-technology.io/dsl/codegen-readme.html#what-are-the-rosetta-code-generators

Given rosetta-cdm is not open, I think you need to update the documentation to say it's closed source. Or just open the rosetta-cdm repository.

**Comment by naddison36** [comment]
The README of this project states "The CDM is designed to be shared openly across all industry participants, hence the name Common.
The CDM is hosted separately from the Rosetta DSL in its own repository."

How is the CDM open when it's in a private repository?
