### ISSUE TITLE
RosettaNamed should not collide when in different name spaces

### ISSUE THREAD

**Issue by minesh-s-patel** [REGnosys/rosetta-dsl#114]
The below will currently cause a validation error.
```
namespace A

type Foo:
    f string (1..1)
```

```
namespace B

type Foo:
    g string (1..1)
```

In order to properly address this, we need to correctly implement the namespace concept.

High level description:
- Each file should have a name space
- 2 files can have the same namespace
- There should exist a default namespace (i.e. no name space def or a default marker)
  - Default namespaces will be auto imported to all model files (this is to address basictypes.rosetta)
- On each file, we should be able to import a set of namespaces. Once we do this, all types and funcs will be available
- We should have the correct validation errors when a type name clashes from 2 different namespaces
- (optional) you should be able to use a qualified name when referring to a type that is not imported ( e.g. common.Party where common is the name space and Party is the type)

**Comment by dhuebner** [comment]
@minesh-s-patel Will the namespace reflect the java packages? If so I would propose to set a proper namespace in the basictypes.rosetta. This namespace will become the default implicit import (similar to java.lang.*)

**Comment by minesh-s-patel** [comment]
@dhuebner 
I though in Java, we would have a base package called `com.rosetta`. Any `.rosetta` file that did not have a namespace would be generated there.

The name space in the cdm project would just change to `cdm` and the code gen would concat that to the base java package making `com.rosetta.cdm`.

All generated java classes would have an implicit import to `com.rosetta.*` that includes `.rosetta`s without namespaces.

Does that make sense? And do you agree?

**Comment by minesh-s-patel** [comment]
Actually - thinking about it further - I think i prefer the implicit `java.lang.*` idea.

**Comment by dhuebner** [comment]
@minesh-s-patel `namespace` is a mandatory grammar rule, so there should not be a rosetta resource without it, except in test cases.
