### ISSUE TITLE
Warning in function conditions, if condition could be positioned directly on the type

### ISSUE THREAD

**Issue by lolabeis** [REGnosys/rosetta-dsl#116]
When a pre- or post-condition operates on a stand-alone object (e.g. just the output), suggest that the condition could be positioned on the data type directly.

This may not always apply (the condition on a stand-alone object could be context-specific to the function), which is why a warning is appropriate.

As a starter, we would like to check whether we have any such occurence in the current CDM code-base.

**Comment by SimonCockx** [comment]
Closing in favor of https://github.com/REGnosys/rosetta-dsl/issues/389
