### ISSUE TITLE
Display validation error for error in synonym syntax

### ISSUE THREAD

**Issue by lolabeis** [REGnosys/rosetta-dsl#117]
Errors in synonym syntax should be propagated as validation errors.

For instance: using "path.value" instead of "path->value" in conditional mapping syntax is incorrect (following recent changes to make synonym syntax consistent), but only shows up as a compilation issue downstream.

**Comment by dhuebner** [comment]
@lolabeis I see some tests that check following:

`[synonym FpML value "FooSyn" set when "../relative/path/to/some/value" is absent]`

Is that something we need to support?

**Comment by lolabeis** [comment]
@dhuebner The idea behind this issue is that it should't just be tests, but be part of the "Scoping and Validation" feature of the DSL that provides immediate feedback to the user.

**Comment by dhuebner** [comment]
merged
