### ISSUE TITLE
MetaFields generate only once per build and only for current namespace

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#125]
MetaFields generator collects all the visible information about namespaces and metatypes. This should be done only once per build. 

As we now use namespaces we must also handle only the current resource namespace. In other words if generator is running for resource `namespace org.isda.cdm.test` we should not regenerate MetaFields for `namespace org.isda.cdm`

**Comment by dhuebner** [comment]
Will be fixed with #115

**Comment by SimonCockx** [comment]
The issue persists. It is currently tracked in https://github.com/REGnosys/rosetta-dsl/issues/139.
