### ISSUE TITLE
Introduce new builtin type map

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#129]
In order to work with `group by` return value `MapperGroupBy` we need a new built-in type. 
Right now it is not possible to pass a grouped value from one function to an other. This means we loose important information without which the comparison is not possible.

**Comment by SimonCockx** [comment]
The `group by` syntax is removed since https://github.com/REGnosys/rosetta-dsl/pull/328, so this is out-dated.
