### ISSUE TITLE
Navigate from Dispatch Functions to the parent

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#29]
When reading a dispatch function, I want to know what are the inputs and outputs attributes that are being referenced. Can we create content assist to to display such information or provide an ability to click and navigate to the parent function?

**Comment by dhuebner** [comment]
Good Idea!

**Comment by dhuebner** [comment]
I part of the ca_for_imports_121 branch

**Comment by SimonCockx** [comment]
Closed by https://github.com/REGnosys/rosetta-dsl/pull/124
