### ISSUE TITLE
Use the same starting point in all conditions

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#36]
For all conditions the first expression should be either an attribute or a function call.
Currently for datarules we use:
```
data Foo: 
    attr1:  int
    attr2: string
    condition Foo_rule_1:
		if Foo -> attr1 exists
		then Foo -> attr2 exists;
```

**Comment by jim-h-wang** [comment]
Agree. In the new syntax, I can't think of a use-case where we will to reference the Type within an Expression. Once we have migrated everything, we look to remove support for references to Type in the grammar. 

Your data rule example should then look per the below:

```java
data Foo: 
    attr1:  int
    attr2: string
    condition Foo_rule_1:
		if attr1 exists
		then attr2 exists;
```

**Comment by dhuebner** [comment]
Still needed in synonyms  `rosettaPath = WorkflowEvent -> eventIdentifier -> assignedIdentifier -> identifier`

**Comment by SimonCockx** [comment]
I'm closing this as the syntax mentioned by @jim-h-wang has been supported for a long time now.
