### ISSUE TITLE
Core and Rule syntax has duplicated functionality

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#397]
# Core and Rule syntax harmonisation

The Core syntax contains functionality for specifying models (e.g., types, attributes etc), expressions, and functions.
The Rule syntax contains functionality for specifying reports, and reporting rules.

Although each syntax has a separate purpose, there is an amount of overlap where the same functionality has been implemented in both syntaxes with different keywords and different underlying code. The differing syntax can be confusing for users, and different underlying code is inefficient to support and maintain.

The functionality that is duplicated in the Rule syntax is mostly used in expressions for extracting and filtering data required for creating reports.

**Comment by hugohills-regnosys** [comment]
Proposal for harmonising Core and Rule syntax
https://github.com/REGnosys/rosetta-dsl/wiki/Core-and-Rule-Syntax-Harmonisation

**Comment by minesh-s-patel** [comment]
@hugohills-regnosys Great proposal.

**Comment by lolabeis** [comment]
Great proposal. A few suggestions:
- In a simple expression where you can write more concisely: `extract [ TradeFor Event ]`, is it not possible also to get rid of the square brackets and just allow to write `extract TradeForEvent`? Obviously in the more general case, e.g. if you use nesting or specify an item value name, you would still require square brackets.

**Comment by hugohills-regnosys** [comment]
> * In a simple expression where you can write more concisely: `extract [ TradeFor Event ]`, is it not possible also to get rid of the square brackets and just allow to write `extract TradeForEvent`?

I think it would be possible.  There's a trade-off between having different syntax options (e.g. optional syntax changes depending on complexity of the logic) vs a single (but more complex) syntax that covers all logic.

**Comment by hugohills-regnosys** [comment]
> * Consider changing `item` -> `this` (since the element in question may not always be an "item" from a list)

I wonder if we could find another word that covers both cases?  Using `this` may cause some confusion as it has a different meaning in other languages (it often refers to the encapsulating object).

**Comment by hugohills-regnosys** [comment]
> * In the example where you specify both the function inputs and outputs, in theory we could omit having to specify a name / type for the output since it's given by the function's expression

Yes, it would be possible.  Something like this?
```
reporting rule FloatingRateForSpreadType:
    [regulatoryReference ESMA EMIR Refit table "2h" dataElement "87"]
    inputs: 
        reportableEvent ReportableEvent (1..1)
        spreadType SpreadTypeEnum (1..1)
    return:
      extract [ TradeForEvent ]
      extract [ ProductForTrade ]
      extract [ InterestRateLeg1 ]
      extract [ item -> rateSpecification -> floatingRate -> initialRate ]
      filter  [ item -> priceExpression -> spreadType = spreadType ]
      extract [ item -> amount ]
      only-element
```
If we implement the JSON-like constructor syntax proposal, then we could theoretically get rid of all the `set`/`add`, and instead the `return` statement would construct the output object with the JSON-like constructor syntax.

**Comment by lolabeis** [comment]
> Yes, it would be possible. Something like this?
Yes, but I was thinking without the `return:` statement. This is exactly how the rule is written today.

**Comment by SimonCockx** [comment]
> In a simple expression where you can write more concisely: extract [ TradeFor Event ], is it not possible also to get rid of the square brackets and just allow to write extract TradeForEvent? Obviously in the more general case, e.g. if you use nesting or specify an item value name, you would still require square brackets.

To give my view on this:
In a sense, I don't see writing `extract TradeForEvent` as deviating from "the general case". In general I would say that `extract` is a binary operation that takes an expression as left argument and a *function reference* as right argument, i.e.,
```
<expression> extract <function reference>
```
Here, `<function reference>` can be either the name of an existing function (e.g., `TradeForEvent`) or a new inline function (e.g., `[item -> amount]`). When interpreting something in brackets as an inline function with a single parameter called `item`, the distinction between both cases fades away.

In XText, this would correspond to something like this: (simplified)
```
ExtractExpression returns RosettaExpression:
  left=RosettaExpression 'extract' right=FunctionReference
;

FunctionReference:
  {InlineFunction} '[' body=RosettaExpression ']'
  | {NamedFunctionReference} reference=[Function]
```

**Comment by lolabeis** [comment]
> The downside would be that it is not possible to validate the type or cardinality of the output.

Yes, but you're already allowing for this in the single-input scenario. All I'm proposing is to decouple the need to specify inputs from that to specify the output.

**Comment by rvincentISDA** [comment]
I would like to retain the use of "then" in a combined list of extracts. A non technologist will not always understand that they are chained. 
In addition can you join 2 or more extract and then conduct an extract on the joined list ? The use of parenthesis and then would make things easier. For example
(Extract [ .....] , Extract [ ....]) then Extract [ ....]

**Comment by hugohills-regnosys** [comment]
> I would like to retain the use of "then" in a combined list of extracts. A non technologist will not always understand that they are chained.

We will give this some consideration.

**Comment by SimonCockx** [comment]
> > * Consider changing `item` -> `this` (since the element in question may not always be an "item" from a list)
> 
> I wonder if we could find another word that covers both cases? Using `this` may cause some confusion as it has a different meaning in other languages (it often refers to the encapsulating object).

Some languages use `it` (e.g., Xtend and Kotlin). That's about as neutral as it gets.

**Comment by hugohills-regnosys** [comment]
> In addition can you join 2 or more extract and then conduct an extract on the joined list ? The use of parenthesis and then would make things easier. For example
> (Extract [ .....] , Extract [ ....]) then Extract [ ....]

This Rule syntax is actually implemented as an `or` statement rather than concatenating the results of each `extract` in the brackets.  We have found that this syntax is error prone as it is not explicit about which extract expression should be used.

Code like this:
```
extract ( 
    extract [ .... ], 
    extract [ .... ],
    extract [ .... ]
)
then extract [ .... ] 
```
Should be refactored to this, where the if/else logic is explicit:
```
extract [ 
    if xxx then 
        extract [ .... ]
    else if yyy then    
        extract [ .... ]
    else
        extract [ .... ]
]
then extract [ .... ] 
```

**Comment by lolabeis** [comment]
> Should be refactored to this, where the if/else logic is explicit

+1 to that

**Comment by minesh-s-patel** [comment]
Feedback from ISDA Member:

Consider changing item -> this (since the element in question may not always be an "item" from a list)
I wonder if we could find another word that covers both cases? Using this may cause some confusion as it has a different meaning in other languages (it often refers to the encapsulating object).
 
Could also be `$` :
 
```Map [ $ -> attribute ]```
