### ISSUE TITLE
Generated code to support adding values to lists

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#44]
The below model code will generate java code that does not compile. This is because in order to assign a value to a list (using the current api), we must know which index of that list to assign. 

```
assign-output reset -> after -> updatedContract -> contractualProduct -> economicTerms -> payout -> equityPayout -> rateOfReturn : <"...">
		RateOfReturn( equityPayout )
```

The default behaviour should be to assign to index 0, however we should also support in the syntax a way to assign to an arbitrary index i, i.e. in the below.

```
assign-output reset -> after -> updatedContract -> contractualProduct -> economicTerms -> payout -> equityPayout[1] -> rateOfReturn : <"...">
		RateOfReturn( equityPayout )
```

**Comment by dhuebner** [comment]
@jim-h-wang Can we close it?

**Comment by jim-h-wang** [comment]
@dhuebner 

We have not yet implemented the below into the object code generators (so generated code that assigns lists is still broken):

```

public EventBuilder addParty(List<Party> party) {
            if(this.party == null){
                this.party = new ArrayList<>();
            }
            for (Party aprtyToAdd : party) {
                this.party.add(aprtyToAdd.toBuilder());
            }
            return this;
        }
```

**Comment by dhuebner** [comment]
Works in #62

**Comment by dhuebner** [comment]
One part is still missing:
```
assign-output reset -> before -> updatedContract -> contractualProduct -> economicTerms -> payout -> equityPayout[2] :
```

Should add an entry at index `2` 
```
resetHolder
			.getOrCreateBefore().getOrCreateUpdatedContract().getOrCreateContractualProduct().getOrCreateEconomicTerms().getOrCreatePayout()
			.addEquityPayout(MapperS.of(equityPayout).get(), 2);
```

We do not support indexed adding in the Builder API

**Comment by dhuebner** [comment]
@jim-h-wang Should  `equityPayout[2] : xyz` replace an element at index 2 or just add a new?

**Comment by jim-h-wang** [comment]
@dhuebner 
Replace if it already exists, add a new one if not.
