### ISSUE TITLE
Harmonisation addendum

### ISSUE THREAD

**Issue by SimonCockx** [REGnosys/rosetta-dsl#455]
Addendum to https://github.com/REGnosys/rosetta-dsl/issues/397.

The harmonisation proposal is all about maintainability. The more consistent we make the core syntax and the rule syntax, the easier it is to maintain.

There are five differences which we would like to mend:
1. Explicit parameter names and unnamed parameters
2. Explicit output specification
3. Brackets and omission of parameters
4. Colons
5. Starting an expression with `extract`

For each of these points, I show the current difference between the syntaxes, I go over potential harmonisations, and I evaluate these proposals based on the following qualities:
- Understandability: as a modeller, I want to easily understand the model. There should be a good way and *only one good way* of writing a function or rule. Having multiple ways of writing the same hurts understandability.
- Conciseness: as a modeller, I don't want to write verbose code.
- Expressiveness: as a modeller, I want access to all DSL operations.
- Information content: as a modeller, I would like the DSL to verify correctness of the code I'm writing and provide me with user-friendly feedback. The more information the DSL has, the better it can do this.

## 1. Explicit parameter names and unnamed parameters
The main difference between parameter naming is as follows.
- Core syntax:
    - Input parameters must be named explicitly.
    - Item parameters may be named explicitly.
    - Unnamed parameters are referenced with `item`.
- Rule syntax:
    - Input parameters are never named explicitly.
    - Item parameters are never named explicitly.
    - Unnamed parameters are referenced with their type name (e.g., `ReportableEvent`).

Combinations and variants are possible too:
- Variant 1A:
    - Input parameters may be named explicitly.
    - Item parameters may be named explicitly.
    - Unnamed parameters are referenced with their type name.
- Variant 1B:
    - Input parameters must be named explicitly.
    - Item parameters must be named explicitly.
    - Unnamed parameters don't exist.

### Examples
Rule syntax:
```
reporting rule Rule
    [docReference xya 123]
    
    TradeForEvent(ReportableEvent)
        extract [ Trade -> tradeableProduct -> product ]
        extract [
            if HasUnderlier(Product)
            then UnderlierForProduct(Product) 
            else Product
        ]
```
Note: to make the comparison just about parameters, I added brackets and left out the first `extract`. This is actually not pure rule syntax.

How it would look like with the current core syntax:
```
reporting rule Rule
    [docReference xya 123]
    inputs: 
        reportableEvent ReportableEvent (1..1)
    output:
        result Product (1..1)
    
    set result:
        TradeForEvent(reportableEvent)
            extract [ item -> tradeableProduct -> product ]
            extract product [
                if HasUnderlier(product)
                then UnderlierForProduct(product) 
                else product
            ]
```

Variant 1A:
```
reporting rule Rule
    [docReference xya 123]
    inputs: 
        reportableEvent ReportableEvent (1..1)

    TradeForEvent(reportableEvent)
        extract [ Trade -> tradeableProduct -> product ]
        extract product [
            if HasUnderlier(product)
            then UnderlierForProduct(product) 
            else product
        ]
```

Variant 1B:
```
reporting rule Rule
    [docReference xya 123]
    inputs: 
        reportableEvent ReportableEvent (1..1)

    TradeForEvent(reportableEvent)
        extract trade [ trade -> tradeableProduct -> product ]
        extract product [
            if HasUnderlier(product)
            then UnderlierForProduct(product) 
            else product
        ]
```

Main idea: for maintainability, we need to settle on a single option!

### Evaluation

|Core syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | ++-   | Names may be chosen arbitrarily to convey meaning. However, having to choose between `item` and an explicit name adds to the complexity. |
|Conciseness        | -     | A modeller has to specify an `inputs` section. They also either have to write a parameter name at every `extract` expression, or use the less understandable `item` keyword. |
|Expressiveness     | ++    | A modeller has access to all DSL operations and they can specify parameters with multiple cardinality. |
|Information content| ++    | The inputs have their type and cardinality specified, so their correct usage can be checked. |

|Rule syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | +     | Parameters are named after their type, which conveys some meaning. |
|Conciseness        | ++    | A modeller doesn't have to specify inputs or parameter names for `extract` expressions. |
|Expressiveness     | --    | A modeller can't use nested `extract`/`filter`/... operations and they don't have access to the `reduce` operation. They can also not write rules that accept more than one parameter, or parameters of multiple cardinality. |
|Information content| +     | Cardinality of inputs is assumed to be `(1..1)`. |

|Variant 1A          | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | ++--  | Names may be chosen arbitrarily to convey meaning. However, having optional inputs and `item` names adds to the complexity. |
|Conciseness        | ++    | A modeller doesn't have to specify inputs or parameter names for `extract` expressions. |
|Expressiveness     | ++    | A modeller has access to all DSL operations and they can specify parameters with multiple cardinality. |
|Information content| +(+)  | Depends on whether parameters are specified explicitly or not. |

|Variant 1B          | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | ++    | Names may be chosen arbitrarily to convey meaning. |
|Conciseness        | -     | A modeller has to specify an `inputs` section. They also have to write a parameter name at every `extract` expression. |
|Expressiveness     | ++    | A modeller has access to all DSL operations and they can specify parameters with multiple cardinality. |
|Information content| ++    | The inputs have their type and cardinality specified, so their correct usage can be checked. |

Notes:
- Omitting parameters is not possible when parameters are named.
- Inlay type/cardinality hints may help with understandability in the future.

## 2. Explicit output specification

The main difference between output specification is as follows.
- Core syntax:
    - Output is named.
    - The intended output type and cardinality are specified.
- Rule syntax:
    - Output is not named.
    - The intended output type and cardinality are not specified.

Combinations and variants are possible too:
- Variant 2A:
    - Output is not named.
    - The intended output type and cardinality are specified.

See examples of current syntaxes in section 1.

Variant 2A (combined with 1A):
```
reporting rule Rule
    [docReference xya 123]
    inputs: 
        reportableEvent ReportableEvent (1..1)

    return Product (1..1):
        TradeForEvent(reportableEvent)
            extract [ Trade -> tradeableProduct -> product ]
            extract [
                if HasUnderlier(Product)
                then UnderlierForProduct(Product) 
                else Product
            ]
```
(alternative: `extract Product (1..1): ...` to really say "I'm extracting a product from a reportable event.")

### Evaluation

|Core syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | /     | I'm not the right person to ask. |
|Conciseness        | -     | An `output:` section with a name, type and cardinality has to be specified. |
|Expressiveness     | +     | Naming the output variable gives the opportunity to have multiple `set`/`add` statements, which allows the modeller to override specific properties of a large object in a concise manner. |
|Information content| +     | The output expression can be validated against the intended type and cardinality. |

|Rule syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | -     | It is not clear what a rule should return. |
|Conciseness        | ++    | No output information needs to be specified. |
|Expressiveness     | -     | It is not possible to override single properties of large objects. |
|Information content| --    | The output expression *cannot* be validated against the intended type and cardinality. Furthermore, it becomes hard to provide useful feedback because the DSL cannot pinpoint at which point in a chain of rules a type error occurred. |

|Variant 2A         | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | +     | It is immediately clear what the rule should return. |
|Conciseness        | +     | No separate `output` section needs to be defined. |
|Expressiveness     | -     | It is not possible to override single properties of large objects. |
|Information content| +     | The output expression can be validated against the intended type and cardinality. |

Notes:
- Inlay type/cardinality hints may help with understandability in the future.

## 3. Brackets and omission of parameters
The way `extract` works in the core syntax and the rule syntax is conceptually different. WARNING: semi-techy explanation incoming!

In the rule syntax, `extract` in
```
extract
    if HasUnderlier(Product)
    then UnderlierForProduct(Product) 
    else Product
```
means: "given the output of previous statement of type `Product`, evaluate the following expression". The following:
```
extract UnderlierForProduct
```
is syntactic sugar for `extract UnderlierForProduct(Product)`. (i.e., you can omit the parameter if the argument of `extract` is just another rule)

In the core syntax, `extract` in
```
input extract product [
    if HasUnderlier(product)
    then UnderlierForProduct(product) 
    else product
]
```
means: "evaluate the left expression, and pass its items one by one to the given function", where `product [...]` is a concise way of defining a function with a single parameter `product` (a so-called *inline* function). In the same way, the following:
```
input extract UnderlierForProduct
```
means "evaluate the left expression, and pass its items one by one to `UnderlierForProduct`". It's not syntactic sugar, but it's just another way of passing a function to `extract`. Here, `UnderlierForProduct` is functionally equivalent with the inline function `product [ UnderlierForProduct(product) ]`.

The main difference between the usage of `extract` (and similar) expressions is as follows.
- Core syntax:
    - The right argument of `extract` is a function. It can either be inline (with brackets) or an existing function name.
    - There is no syntactic sugar for parameter omission.
- Rule syntax:
    - The right argument of `extract` is an expression.
    - There is syntactic sugar for parameter omission if the expression is another rule.

Combinations and variants are possible too:
- Variant 3A:
    - The right argument of `extract` is a function. It can either be inline (with brackets) or an existing function name.
    - Parameter omission is syntactic sugar for passing `item`.

### Examples 

Suppose we have a list `people` of the following type.
```
type Person:
    favoriteNumbers int (1..*)
```
Example: find all the cool people (i.e., people who have at least 3 favourite numbers greater than 999)

Core syntax (also variant 3A):
```
func FindCoolPeople:
    inputs:
        people Person (0..*)
    output:
        coolPeople Person (0..*)
    
    add coolPeople:
        people
            filter person [
                person -> favoriteNumbers
                    filter n [ n > 999 ]
                    count >= 3
            ]
```

Rule syntax: impossible to implement!

Example from Hugo:
```
func CompareNumberLists:
    inputs:
        list1 number (0..*)
        op CompareOp (1..1)
        list2 number (0..*)
    output:
        result boolean (1..1)

    // each item in list1 must be compared to each item in list2            
    set result:
        list1
            extract list1Item [ // take each item in list1 (parameter is list1Item)
                // compare list1Item to each item in list2 (parmeter is list2Item)
                list2
                    extract list2Item [ CompareNumbers( list1Item, op, list2Item ) 
                ]
            ]
            all = True
```

### Evaluation

|Core syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | /     | I'm not the right person to ask. |
|Conciseness        | +-    | May pass a named function directly. Otherwise, however, it needs brackets, and optionally a parameter name. |
|Expressiveness     | ++    | Supports nested functions. |
|Information content| /     | NA. |

|Rule syntax        | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | /     | I'm not the right person to ask. |
|Conciseness        | +     | No brackets. |
|Expressiveness     | -     | Operations that require nested inline functions cannot be expressed. |
|Information content| /     | NA. |

|Variant 3A         | Score | Reasoning                   |
|------------------ | ----- | --------------------------- |
|Understandability  | /     | I'm not the right person to ask. |
|Conciseness        | ++-   | Not necessary to specify the parameter passed to functions. May pass a named function directly. Otherwise, however, it needs brackets, and optionally a parameter name.  |
|Expressiveness     | ++    | Supports nested functions. |
|Information content| /     | NA. |

Notes:
- It might not be necessary to have full expressiveness in the rule syntax. The question is how many times nested operations are useful for DRR, and whether it's okay to implement them as a function or not.
- An entirely different approach to reduce the number of brackets is by adding new interpretations of what we consider a function. For example, we could intepret
  ```
  Trade -> tradeableProduct -> product
  ```
  as a function equivalent to `trade [ trade -> tradeableProduct -> product ]`. In that way, we wouldn't need to write brackets whenever we just need to extract an attribute:
  ```
  trades
      extract Trade -> tradeableProduct -> product
  ```

## 4. Colons
Only a small point, but currently the body of a function starts with a colon, whereas reporting rules don't have one.
```
func Rule:
    ... // body of the function

reporting rule Rule
    ... // body of the rule
```
For consistency's sake, we might want to add a colon to reporting rules.

## 5. Starting an expression with `extract`
Again, the way `extract` works in the core syntax and the rule syntax is conceptually different. I'll demonstrate this particular difference with an example.

### Examples
Rule syntax:
```
reporting rule Rule
    [docReference xya 123]
    
    extract TradeForEvent(ReportableEvent)
    then extract Trade -> tradeableProduct -> product
    then extract
        if HasUnderlier(Product)
        then UnderlierForProduct(Product) 
        else Product
```
Notice that the first `extract` expression doesn't explicitly specify an input.

Core syntax:
```
func F:
    inputs: 
        reportableEvent ReportableEvent (1..1)
    output:
        result Product (1..1)
    // way 1 (compared to the rule syntax, we don't need to start with `extract`)
    set result:
        TradeForEvent(reportableEvent)
            extract [ item -> tradeableProduct -> product ]
            extract product [
                if HasUnderlier(product)
                then UnderlierForProduct(product) 
                else product
            ]
    // way 2 (explicitly write the input; looks more similar to rule syntax)
    set result:
        reportableEvent
            extract TradeForEvent
            extract [ item -> tradeableProduct -> product ]
            extract product [
                if HasUnderlier(product)
                then UnderlierForProduct(product) 
                else product
            ]
```

Open questions:
- Do we prefer starting with `extract`?  E.g.,
```
    set result:
        extract reportableEvent
        extract TradeForEvent
```
- Which is more clear?
- What is the best way to harmonise this difference?

**Comment by hugohills-regnosys** [comment]
Additional example to show the impact of using type as parameter name.

Current syntax (parameter can be named `item` or named parameter, nested functions allowed):

```
func CompareQuantityByUnitOfAmount:
    inputs:
        quantities1 Quantity (0..*)
        op CompareOp (1..1)
        quantities2 Quantity (0..*)
        unitOfAmount UnitType (1..1)
    output:
        result boolean (1..1)

    // each item in list1 must be compared to each item in list2            
    set result:
        quantities1
            filter [ item -> unit = unitOfAmount ]
            map [ item -> value ]
            extract list1Item [
                quantities2
                    filter [ item -> unit = unitOfAmount ]
                    map [ item -> value ]
                    extract list2Item [ CompareNumbers( list1Item, op, list2Item ) ]
            ]
            all = True
```

Rule-like syntax (parameter must be type name, nested functions not used due to name clash):

```
func CompareQuantityByUnitOfAmount:
    inputs:
        quantities1 Quantity (0..*)
        op CompareOp (1..1)
        quantities2 Quantity (0..*)
        unitOfAmount UnitType (1..1)
    output:
        result boolean (1..1)

    // each item in list1 must be compared to each item in list2            
    set result:
        quantities1
            filter Quantity -> unit = unitOfAmount
            extract Quantity -> value
            extract CompareListToNumber( quantities2, op, Quantity ) // separate function due to name clash
            all = True

func CompareListToNumber:
      inputs:
        quantities Quantity (0..*)
        op CompareOp (1..1)
        quantityItem Quantity (1..1)
    output:
        result boolean (1..1)  

    set result:
        quantities
            extract CompareNumbers( Quantity -> value, op, quantityItem )
            all = True
```

**Comment by SimonCockx** [comment]
Post-discussion: our preference is with option 2.a, i.e., we force an explicit input type on rules. This will greatly simplify the harmonisation of both syntaxes.
