### ISSUE TITLE
Validation for choice rules

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#46]
Validation:
- [x] Validate at least two attributes passed to choice 
- [x] condition : oneOf // name mandatory?  <-- NO

_Originally posted by @dhuebner in https://github.com/REGnosys/rosetta-dsl/issues/40#issuecomment-530273137_

**Comment by SimonCockx** [comment]
Closed by https://github.com/REGnosys/rosetta-dsl/pull/132
