### ISSUE TITLE
Inlay Hist Support for Rosetta LSP

### ISSUE THREAD

**Issue by minesh-s-patel** [REGnosys/rosetta-dsl#461]
## Context
The Rosetta LSP (com.regnosys.rosetta.ide module) has out of the box support for the LSP protocol. The [lsp4J](https://github.com/eclipse/lsp4j) library fully supports Inlay hints however, the integration for InlayHints is notably missing from the XText stack.

## Idea
Create a very easy interface/abstract class to implement that allows us to add an inlaylint to any ECoreObject in the same way as we can add validation checks.

## Example

```
  @InlayHint
  public InlayHint rosettaFunctionInlay (Function func) {
    return createInlay(func, "my inlay hint");
  }

```

That would show:
![image](https://user-images.githubusercontent.com/19842097/205594829-8cab9fb3-12ec-454a-af5e-c3f4f1b9024e.png)

**Comment by SimonCockx** [comment]
Infrastructure implemented by https://github.com/REGnosys/rosetta-dsl/pull/460
