### ISSUE TITLE
Find a better name for toOne

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#49]
We have a possibility to convert a Multi type (List) to a single value. 
In fact the `MapperC.get()` function is used where if the list is of size 1 the first element will be retuned null otherwise. 
Language feature is called `toOne` we are looking for a better name.

**Comment by SimonCockx** [comment]
This feature has been named `only-element`. Closed by https://github.com/REGnosys/rosetta-dsl/pull/47.
