### ISSUE TITLE
Support for ISO 20022 data types

### ISSUE THREAD

**Issue by SimonCockx** [REGnosys/rosetta-dsl#512]
The ISO 20022 standard for financial industry messages defines a series of data types that represent variants of the basic `number` and `string` types from Rosetta. Examples include the [`Max4AlphaNumericText`](https://www.iso20022.org/standardsrepository/type/Max4AlphaNumericText) type, which is a string limited to alpha numeric characters that may contain up to four characters, or the [`Max3Number`](https://www.iso20022.org/standardsrepository/type/Max3Number), which is an integer having at most 3 digits. In order to fully support the ISO 20022 standard, our goal is to give modellers a means of modelling such types directly in Rosetta.

## Structure of this proposal

Below, I illustrate the different requirements for ISO 20022 support by going through several characteristic examples of data types defined in the standard. Based on these examples, I lay out a proposal for additional Rosetta syntax that would allow us to fully model these data types in a generic way. In further comments I zoom in on technical details of how these changes would affect the existing semantics and type system of Rosetta expressions.

## What this proposal does _not_ aim to achieve

ISO 20022 is, at its core, a standard for representing data _serially_, e.g., as XML or JSON. Often, the specification talks about formatting that does not have semantic implications. For example, the specification defines [`PercentageRate`](https://www.iso20022.org/standardsrepository/type/PercentageRate) as "a rate expressed as a percentage, that is, in hundredths[...]". This, however, has no semantic significance, and is only important for representation purposes, e.g., during serialisation and deserialisation. Semantically `PercentageRate` can be treated as a regular `number`, so I consider such requirements to be out of scope for this proposal.

## Requirements by example

I consider three different categories of ISO data types.

### Category: data types that already have a good representation in Rosetta

The ISO standard defines plenty of data types such as [`QueryType2Code`](https://www.iso20022.org/standardsrepository/type/QueryType2Code) and [`ActiveCurrencyCode`](https://www.iso20022.org/standardsrepository/type/ActiveCurrencyCode) which can already be properly modelled as an `enum` or a `string`. These data types require no further changes to the DSL.

### Category: data types that look like Rosetta basic types

This includes data types such as [`ISODate`](https://www.iso20022.org/standardsrepository/type/ISODate) and [`DecimalNumber`](https://www.iso20022.org/standardsrepository/type/DecimalNumber), for which we might be tempted to choose our built-in types `date` and `number` respectively. However, when it comes to numeric types, there are important differences.

**The specification of the [`Number`](https://www.iso20022.org/standardsrepository/type/Number) data type** mentions the following:
> Number of objects represented as an integer.
> - total number of digits: 18
> - number of digits in fractional part: 0

Right now, integers in Rosetta are represented by `int`. However, whereas the ISO standard mentions a size of 18 digits, our documentation lacks such a precision. Our Java code generator uses a 32-bit signed integer, which can only hold up to 10 decimal digits.

**The specification of the [`DecimalNumber`](https://www.iso20022.org/standardsrepository/type/DecimalNumber) data type** mentions the following:
> Number of objects represented as a decimal number, for example 0.75 or 45.6.
> - total number of digits: 18
> - number of digits in fractional part: 17

Right now, decimal numbers in Rosetta are represented by `number`. Similarly, whereas the ISO standard mentions a precision of 18 digits, our documentation lacks such clarification. Our Java code generator uses arbitrary precision decimal numbers, except when comparing them, in which case a precision of 9 digits is used (at which point the code will throw a runtime exception if the precision of the number of digits is any higher than 9).

For all practical purposes, [`ISODate`](https://www.iso20022.org/standardsrepository/type/ISODate) may be mapped to `date`, [`ISOTime`](https://www.iso20022.org/standardsrepository/type/ISOTime) may be mapped to `time`, and [`ISODateTime`](https://www.iso20022.org/standardsrepository/type/ISODateTime) may be mapped to `zonedDateTime`.

### Category: types with additional conditions

Examples include [`Max5PositiveNumber`](https://www.iso20022.org/standardsrepository/type/Max5PositiveNumber), which describes a positive number consisting out of 5 digits, and [`Min8Max28NumericText`](https://www.iso20022.org/standardsrepository/type/Min8Max28NumericText), which describes a string consisting out of 8 to 28 numeric characters.

For string types, there exist three kinds of conditions:
- the string must contain at least a number of characters,
- the string must contain at most a number of characters,
- the string must match a specific regular expression.

For number types, there exist two kinds of conditions:
- the number must be greater than a specific bound,
- the number must be less than a specific bound.

## Proposal

My proposal consists out of two parts:
1. Parameterize the `number` and `string` type in order to support different precisions and conditions.
2. Support _type synonyms_ in order to refer to these parameterized types in a clear and user-friendly way.

### 1. Parameterize `number` and `string` type

Example: a positive decimal number with a precision of 18 that is at most 5000:
`number(digits=18, fractionalDigits=17, min=0, max=5000)`
Notes:
- All arguments are optional. Default values:
    - `digits=18`
    - `fractionalDigits=digits-1`  (represents the _maximum_ number of fractional digits)
    - there is no `min` or `max` bound.
- `int` is shorthand for `number(fractionalDigits=0)`

Example: a string with 3 to 5 characters that must be alphanumeric:
`string(minLength=3, maxLength=5, pattern=/[a-zA-Z0-9]*/)`
Notes:
- All arguments are optional. By default, there is no constraint.

### 2. Support for type synonyms
E.g.,
```
dataType max3Number = int(digits=3)
dataType positiveNumber = int(min=0)
dataType max4AlphaNumericText = string(minLength=1, maxLength=4, pattern=/[a-zA-Z0-9]{1,4}/)
```

Modellers can then refer to these types, e.g.,
```
type RequestHandling:
  statusCode max4AlphaNumericText (1..1)
  description string (0..1)
```

Furthermore, type synonyms can be used to improve the readability of hovering and inlay type hints, e.g., instead of displaying a verbose `string(minLength=1, maxLength=4, pattern=/[a-zA-Z0-9]{1,4}/)` type, we can instead display the type synonym `max4AlphaNumericText`.

Together, these two additional features would allow modellers to implement all necessary ISO 20022 data types (say, in `standards/iso20022/datatypes`), and then start using these types directly in their models.

**Comment by SimonCockx** [comment]
Coming soon: technical implications for the subtype relation, conversions and adjustements to existing operations.

**Comment by SimonCockx** [comment]
## Adjust type system and semantics of existing operations

- Comparisons of the form `a = b` and `a < b` are only allowed if the bounds of `a` and `b` overlap. Precision (`digits` and `fractionalDigits`) are not considered during comparisons, i.e., they are compared by adding trailing zero's to the number with the least precision. (`1.5` is equal to `1.500`)
- `a + b` for numbers results in `number(digits=max(da, db) + 1, fractionalDigits=max(fa, fb), min=mina + minb, max=maxa + maxb)`. If a bound is absent, the resulting bound is absent as well.
- `a + b` for strings results in `string(minLength=mina + minb, maxLength=maxa + maxb, pattern=pa + pb)`. If a bound is absent, the resulting bound is absent as well. If a pattern is absent, the resulting pattern is absent as well.
- `a * b` results in `number(digits=da + db, fractionalDigits=fa + fb, min=min(mina*minb, mina*maxb, maxa*minb, maxa*maxb), max=...)`.
- Similar for `a - b` and `a / b`.
- `a join b` results in a `string` with default parameters.
- `a sum` results in a `number` with default parameters, except for the number of fractional digits, which is the same as that of the items of `a`.

Note that for the last two operations we could do better if we knew the cardinality of `a`. However, this would first require enhancing our type system with further support for reasoning about cardinality, as planned in the fourth phase of [Project: DSL Type Formalisation](https://github.com/REGnosys/rosetta-dsl/wiki/Project:-DSL-Type-Formalisation).

**Comment by minesh-s-patel** [comment]
@SimonCockx 

This is a very well thought out proposal and I agree with the conclusion.

**Comment by SimonCockx** [comment]
@lolabeis Interesting question, one which is actually also applicable to our existing subtype relation.

As of now, we do not support overwriting attributes in any way (except for overwriting `ruleReference`s, but that's the only exception). For example, the following will fail
![image](https://user-images.githubusercontent.com/47859223/231078319-451854ee-4899-46f8-97f1-34411da6b23c.png)
with these error messages:
```
Overriding attribute 'a' with type (B) must match the type of the attribute it overrides (A)
Overriding attribute 'n' with type (int) must match the type of the attribute it overrides (number)
```

Since Rosetta objects are immutable, we could support it though, although that's a separate issue.
