### ISSUE TITLE
Enum to string (via displayName) support

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#523]
The syntax should support converting an `enum` to a `string` by calling `displayName`. 

```
enum FloatingRateIndexEnum: 
	AED_EBOR_Reuters displayName "AED-EBOR-Reuters"
	AED_EIBOR displayName "AED-EIBOR"
	AUD_AONIA displayName "AUD-AONIA"
	AUD_AONIA_OIS_Compound_1 displayName "AUD-AONIA-OIS Compound"
	...
```
```
enum InflationRateIndexEnum: 
	AUD_CPI displayName "AUD-CPI" 
	AUS_CPI displayName "AUS-CPI" 
	AUS_HICP displayName "AUS-HICP" 
	BLG_CPI_GI displayName "BLG-CPI-GI" 
	...
```

In DRR, the enums `FloatingRateIndexEnum` and `InflationRateIndexEnum` need to be reported in the same field, so one approach would be to convert to their `displayName` so the reported field is of type `string` which works for both.

Separate note: should it be display-name to be consistent with the other syntax?

**Comment by lkjpm** [comment]
syntax to extract if possible
rateOption -> floatingRateIndex -> displayName

**Comment by hugohills-regnosys** [comment]
Replaced by https://github.com/REGnosys/rosetta-dsl/issues/570
