### ISSUE TITLE
List to single comparison within rules causes validation or code gen error

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#533]
E.g.
```
reporting rule Blueprint1:
    extract 
        if ["A", "B", "C"] all <> Input->str then
            Input-> str

type Input:
    str string (1..1)
```

```
java.lang.NullPointerException
	at com.regnosys.rosetta.generator.java.blueprints.BlueprintGenerator.buildNode(BlueprintGenerator.java:782)
```
because by `typedNode.input.type` is null around xtend line 281.

It's not an issue for core syntax (e.g. inside `func` etc)

**Comment by SimonCockx** [comment]
@hugohills-regnosys I can't reproduce it. Is this still an issue in the latest DSL version?

**Comment by hugohills-regnosys** [comment]
No, it seems to have been fixed in release https://github.com/REGnosys/rosetta-dsl/releases/tag/7.5.0
