### ISSUE TITLE
Create_TradeState does not set required field activityDate on ClosedState when closing position

### ISSUE THREAD

**Issue by adamturski** [REGnosys/rosetta-dsl#542]
I found the bug? in default implementation of Create_TradeState logic when it creates ClosedState for closed position:

Rosetta code for Create_TradeState function
```
	set after -> state -> closedState:
		if contractFormation -> state -> positionState = PositionStatusEnum -> Closed then
		    Create_ClosedState( ClosedStateEnum -> Terminated, empty, empty, empty ) // empty parameters refers to ClosedState dates
```

Create_ClosedState simply sets passed parameters on new ClosedState:
```
type ClosedState:
	state ClosedStateEnum (1..1)
	activityDate date (1..1)
	effectiveDate date (0..1)
	lastPaymentDate date (0..1)
```

In the end such created ClosedState does not pass validation as it does not have required activityDate.

Maybe ClosedState should be created in Create_BusinessEvent where BusinessEvent.effectiveDate and BusinessEvent.eventDate can be used which look like more appropriate fields to set ClosedState.activityDate.

**Comment by hugohills-regnosys** [comment]
Hi Adam, please could you raise these on the FINOS CDM GitHub issues - https://github.com/finos/common-domain-model/issues

**Comment by adamturski** [comment]
@hugohills-regnosys TIcket created https://github.com/finos/common-domain-model/issues/2145
