### ISSUE TITLE
Can PriceSchedule validation allow value 0.0? 

### ISSUE THREAD

**Issue by adamturski** [REGnosys/rosetta-dsl#543]
Currently there are some validation rules for PriceSchedule, especially:
PriceSchedulePositiveFXRate
PriceSchedulePositiveSpotRate
PriceSchedulePositiveCashPrice

which do not allow value 0 as a PriceSchedule value. For example PriceSchedulePositiveCashPrice:
```
if priceExpression -> priceType = PriceTypeEnum -> CashPrice then value > 0
```

For Quantity type there is a validation rule NonNegativeQuantityNonNegativeQuantityAmount which allows 0 as value.

Can such validation rules can be relaxed and allow 0 as a value?

**Comment by hugohills-regnosys** [comment]
Hi Adam, please could you raise these on the FINOS CDM GitHub issues - https://github.com/finos/common-domain-model/issues

**Comment by adamturski** [comment]
@hugohills-regnosys Ticket created https://github.com/finos/common-domain-model/issues/2144
