### ISSUE TITLE
Add cardinality checks

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#56]
1. `Bar( strings )` should error as `strings` has multiple cardinality when single cardinality is expected.
1. `assign-output fooOut : Bar( strings )` should error as the return type of Bar has multiple cardinality when single cardinality is expected.

```haskell
func Foo:
	inputs: strings string (1..*)
	output: fooOut number (1..1)
	assign-output fooOut : Bar( strings )
		
func Bar:
	inputs: string string (1..1)
	output: numbers number (1..*)
```

**Comment by dhuebner** [comment]
Implemented in  #62
