### ISSUE TITLE
Support for to-string and parse string for enums and basic types

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#570]
It would be useful to have the ability to:
- convert enums or basic types to a string
- convert strings to basic types or enums

It would be particularly useful for parsing currency `string` into `ISOCurrencyCodeEnum`, e.g.:

```
func StringToISOCurrencyCodeEnum:
    inputs:
        currency string (1..1)
    output:
        currencyCode ISOCurrencyCodeEnum (0..1)

    set currencyCode: 
        ISOCurrencyCodeEnum from-string currency
```
```
func ISOCurrencyCodeEnumToString:
    inputs:
        currencyCode ISOCurrencyCodeEnum (1..1)
    output:
        currency string (1..1)

    set currencyCode: 
        currencyCode to-string
```
Suggested syntax:
- `<value> to-string` - converts value (which must be a enum or basicType) to a string. 
- `<type> from-string <value>` - parses the value into the specified type (which must be a enum or basicType).

If an enum has a displayName specified then the `to-string`/`from-string` would use that.
For `from-string`, if no matching enum or basic type is found then an empty value would be returned.

**Comment by SimonCockx** [comment]
> <type> from-string <value> - parses the value into the specified type (which must be a enum or basicType).

I'm not sure about the order of `from-string`'s arguments. Having the type first reads more fluently, although having the value first is in a way more consistent with other operations.

> For from-string, if no matching enum or basic type is found then an empty value would be returned.

What about if the type has constraints, e.g., `number(max: 10)`? Should these constraints be validated, and if so, should this result in an empty value if the constraint is violated? E.g., `number(max: 10) from-string "1000"`

**Comment by hugohills-regnosys** [comment]
> I'm not sure about the order of from-string's arguments. Having the type first reads more fluently, although having the value first is in a way more consistent with other operations.

Also not sure on this one.  Some further thoughts..

1. <type> from-string <value> 
  - e.g. `ISOCurrencyCodeEnum from-string "AUD-CPI"`
  - e.g. `int from-string "9"`
  - e.g. `number from-string "3.1415"`
2. <value> from-string <type> 
  - e.g. `"AUD-CPI" from-string ISOCurrencyCodeEnum`
  - e.g. `"9" from-string int`
  - e.g. `"3.1415" from-string number`
3a. <value> to-enum <type> 
  - e.g. `"AUD-CPI" to-enum ISOCurrencyCodeEnum`
3b. <value> to-<type> 
  - e.g. `"9" to-int`
  - e.g. `"3.1415" to-number`

**Comment by SimonCockx** [comment]
> Alternatively, could have more varied (but more descriptive) syntax
> 
>     <value> to-enum <type>
> 
>     "AUD-CPI" to-enum ISOCurrencyCodeEnum
> 
>     <value> to-<type> 
> 
>     "9" to-int
>     "3.1415" to-number
> 

I do like this suggestion. It's more concise and is somewhat more restrictive, making it simpler.

**Comment by SimonCockx** [comment]
Implemented by https://github.com/REGnosys/rosetta-dsl/pull/592
