### ISSUE TITLE
Java code generation for validators can cause stale class files

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#597]
Consider type `Foo` with an attribute `attr` of type string.
```
type Foo:
    attr string (1..1)
```

From this type, a cardinality validator is Java code-generated that checks the cardinality matches what is specified in the model (i.e. 1..1)
```
public class FooValidator implements Validator<Foo> {

	@Override
	public ValidationResult<Foo> validate(RosettaPath path, Foo o) {
		String error = 
			Lists.<ComparisonResult>newArrayList(
				checkCardinality("attr", o.getAttr() != null ? 1 : 0, 1, 1)
			).stream().filter(res -> !res.get()).map(res -> res.getError()).collect(joining("; "));
		
		if (!isNullOrEmpty(error)) {
			return failure("Foo", ValidationResult.ValidationType.CARDINALITY, o.getClass().getSimpleName(), path, "", error);
		}
		return success("Foo", ValidationResult.ValidationType.CARDINALITY, o.getClass().getSimpleName(), path, "");
	}
}
```

Now, if the attribute type is changed from `string` to `number`, it can cause problems with stale Java .class files..  this is because when the model is changed, the code-gen infrastructure regenerated all the Java source files (and then compilation generated new .class files), however blah
```
type Foo:
    attr number (1..1)
```

**Comment by hugohills-regnosys** [comment]
Fixed in https://github.com/REGnosys/rosetta-dsl/pull/596

**Comment by hugohills-regnosys** [comment]
Fixed in https://github.com/REGnosys/rosetta-dsl/pull/596

**Comment by SimonCockx** [comment]
@hugohills-regnosys I could argue that this is no bug in the DSL, but rather a bug in the compilation mechanism of our IDE, which doesn't properly implement incremental compilation. Adding an unnecessary cast to the source file is really a workaround, not a solution, if you ask me. There still might be various edge cases where the same problem occurs.

We should think about fixing the root of the problem, i.e., recompiling all source files that _depend_ on a changed source file (recursively) as well, or just removing incremental compilation and going for a clean compilation each time, if that's not a performance issue.
