### ISSUE TITLE
XSD import tool does not respect `xs:choice`

### ISSUE THREAD

**Issue by SimonCockx** [REGnosys/rosetta-dsl#654]
Example:
```
	<xs:complexType name="TrancheIndicator3Choice">
		<xs:choice>
			<xs:element name="Trnchd" type="Tranche3" />
			<xs:element name="Utrnchd" type="NoReasonCode" />
		</xs:choice>
	</xs:complexType>
```
results in
```
type TrancheIndicator3Choice:

	trnchd Tranche3 (1..1)
	utrnchd NoReasonCode (1..1)
```

Note that the cardinalities should be `(0..1)` and there should be a `one-of` condition. (or an `optional choice` if it's not required?)

**Comment by SimonCockx** [comment]
Duplicate of https://github.com/REGnosys/rosetta-dsl/issues/556

**Comment by hugohills-regnosys** [comment]
https://github.com/finos/common-domain-model/issues/3364
