### ISSUE TITLE
Output object on the Function should be validated

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#69]
The generate java code should run object validation before returning the output object. Validation invocation example [here](https://github.com/REGnosys/isda-cdm-demo/blob/fc80ccddd19aabf7b5c9b5be3b3b55f0812d02d5/src/main/java/com/regnosys/cdm/example/Validation.java#L26:L53)

**Comment by dhuebner** [comment]
@jim-h-wang Should the recursive validation be invoked or the  `choice` `data` rules only for the return object?

What should  happen with the result? Throw an exception or log?

**Comment by jim-h-wang** [comment]
@dhuebner 

> Should the recursive validation be invoked or the choice data rules only for the return object?

Recursive please.

> What should happen with the result? Throw an exception or log?

Exception please.
