### ISSUE TITLE
Add generic ListBuilder to allow implementation of function with list return type

### ISSUE THREAD

**Issue by dhuebner** [REGnosys/rosetta-dsl#71]
A list builder should allow creation and mutation of a list of Rosetta model objects. 

Should also support common Builder API patterns.

**Comment by dhuebner** [comment]
Currently I'm not quite sure we need to support it.

**Comment by SimonCockx** [comment]
We can now build lists in a function with `set` and `add`. https://github.com/REGnosys/rosetta-dsl/pull/335
