### ISSUE TITLE
Support * and / for expressions

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#84]
MapperMaths needs to be updated to support multiplication and division

**Comment by dhuebner** [comment]
@jim-h-wang Do you still missing some cases where it doesn't work? 

https://github.com/REGnosys/rosetta-dsl/blob/master/com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/functions/MapperMaths.xtend#L28

**Comment by jim-h-wang** [comment]
Oh cool - I had missed the fact that you added these! Thanks!
