### ISSUE TITLE
Issue with count in condition

### ISSUE THREAD

**Issue by TomCLForwood** [REGnosys/rosetta-dsl#93]
The function

```
	func Allocate: <"Function specification to create the fully-formed business event of allocating an 	execution based on allocation instructions.">
	

	inputs:
		execution Execution (1..1) <"Block trade to be allocated.">
		allocationInstructions AllocationInstructions (1..1) <"Allocation instructions to be applied.">
		previousEvent Event (1..1) <"Previous event for lineage purposes.">

	output:
		allocationEvent Event (1..1) <"Allocation event containing both the original block trade (with the status set to Allocated) and the set of allocated trades.">

	condition: 
		allocationInstructions -> breakdowns count > 0
```
fails to generate code with the server side error
INFO  [2019-10-16 10:43:21,771] [] com.regnosys.rosetta.generator.RosettaGenerator: Unexpected calling standard generate for rosetta
! java.lang.IllegalArgumentException: RosettaCountOperation is not covered yet.
! at com.regnosys.rosetta.generator.java.function.RosettaFunctionDependencyProvider.functionDependencies(RosettaFunctionDependencyProvider.java:141)
! at com.regnosys.rosetta.generator.java.function.FuncGenerator.lambda$3(FuncGenerator.java:156)

**Comment by TomCLForwood** [comment]
It looks like this case hasn't been implemented yet.

Also the fall through case should probably be an error rather than just info - these should never be occurring in prod

**Comment by dhuebner** [comment]
fixed
