### ISSUE TITLE
Consolidate grammar for Synonyms on Attributes and Enums

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#96]
```Haskell
enum DayCountFractionEnum <"The enumerated values to specify the day count fraction.">
	[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value dayCountFractionScheme_2_2]
{
	ACT_360 displayName "ACT/360" <"Per 2006 ISDA Definitions...">
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, DTCC_11_0, DTCC_9_0, CME_ClearedConfirm_1_17 value "ACT/360"],
```

```Haskell
class Contract key <"A class ...">
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, CME_ClearedConfirm_1_17 meta id path "trade"]
		[synonym FpML_5_10, CME_SubmissionIRS_1_0, CME_ClearedConfirm_1_17, Rosetta_Workbench meta id]
{
	contractIdentifier Identifier (1..*) <"The identifier...">;
		[synonym FpML_5_10, CME_SubmissionIRS_1_0 value partyTradeIdentifier path "trade.tradeHeader"]
		[synonym FpML_5_10, CME_SubmissionIRS_1_0 value partyTradeIdentifier path "tradeHeader"]
		[synonym CME_ClearedConfirm_1_17 value partyTradeIdentifier path "trade.tradeHeader"]
```

1. the `value` on enums are in double-quotes whilst on attributes are not in quotes. Should make consistent and should prefer no quotes where possible. 
2. for attribute synonyms, the `path` is in quotes whilst the `value` is not. Should make consistent and should prefer no quotes where possible. 
3. the dot `.` delimiter on the `path` is inconsistent with the arrow `->` on rosetta attribute paths, I think we should use `->` for all paths if possible

**Comment by dhuebner** [comment]
@jim-h-wang 
1. I'm for using double-quotes. Comment fron the Grammar `the synonymValue is of type STRING to accommodate peculiar values` which is true i.e. `value "ACT/360"`. This will also help keep ValidId exceptional cases reduced, see #101

2. Also here I would say use quotes. There is no benefit for `.` notation, one can not use content assist after `.` and one can't jump to the path segments.

3. see 2.

Afaik we do not really have control over "referenced" values in synonym part, correct me if I'm wrong. If so, we can't really react on syntactically breaking cases for example an arithmetical operator, reserved keyword or even space. Overall, the only practical way I see, is to quote the values.

**Comment by jim-h-wang** [comment]
@dhuebner 

1. Ok, let's use quotes everywhere for consistency. 

2, 3. Sounds like you are in favour of migrating `.` to `->`. For this change, you will need to find usages of the `path` part of the synonym across all repositories. I know at least in rosetta-ingest, we depend on the `.` to perform a `String::split`

**Comment by dhuebner** [comment]
@jim-h-wang 
> depend on the . to perform a String::split

Hopefully some tests will fail if I miss a piece

**Comment by dhuebner** [comment]
@jim-h-wang 
I would also suggest to consolidate the rest of class synonym rule:

```
RosettaSynonymBody:
	( 'value'  (values+=RosettaSynonymValue ',')* values+=RosettaSynonymValue (mappingLogic=RosettaMapping)? 
		| 'hint' (hints+=ValidHint ',')* hints+=ValidHint
		| mappingLogic=RosettaMappingSetTo )
	('meta' (metaValues += ValidID ',')* metaValues += ValidID)?
	('mapper' mapper=ValidID)?
	
;
```

`ValidHint` & `ValidID` are just values which are not referenced or referencing things hance may become a STRING too. Also ValidHint allows `*` at the end but it's never used in cdm, do we still need this? 

I found any usage of SynonymEnumeration:
```
RosettaSynonymEnumeration:
	value = '.' enumValue=STRING
;
```

One test case for that, but the syntax looks really strange:
```
[synonym FpML value Bar."value"]
```

**Comment by jim-h-wang** [comment]
> ValidHint & ValidID are just values which are not referenced or referencing things hance may become a STRING too. Also ValidHint allows * at the end but it's never used in cdm, do we still need this?

I still prefer to not have the quotes if we can avoid them. Changing `ValidId` to `STRING` would mean that all the attribute names would then need quotes. The `*` isn't currently used but we do still plan to make use of it. 

> I found any usage of SynonymEnumeration:

We can remove this grammar, it's unused in the model and not supported in ingestion.
