### ISSUE TITLE
Code generation fails when using 'count' feature

### ISSUE THREAD

**Issue by jim-h-wang** [REGnosys/rosetta-dsl#98]
See https://github.com/REGnosys/rosetta-cdm/pull/524/files for how to reproduce. The symptom is that the Allocate java function no longer generates.

**Comment by dhuebner** [comment]
@jim-h-wang Also starting with an attribute inside a type condition is not yet supported:
Use the same starting point in all conditions #36

**Comment by jim-h-wang** [comment]
> See: Issue with count in condition #93

oops - this is a dupe
